packages:
  - 'packages/*'
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
injectWorkspacePackages: true
minimumReleaseAgeExclude:
  - '@solidjs/vite-plugin@3.0.0-next.41 || 3.0.0-next.42'
  - '@rolldown/binding-openharmony-arm64@1.2.8'
