services:
  server:
    image: ghcr.io/heinergrote/sensor-sim-server:latest
    env_file: .env
    ports:
      - "${PORT:-4000}:${PORT:-4000}"
    volumes:
      - sensor-sim-data:/app/data/storage
    restart: unless-stopped

volumes:
  sensor-sim-data:
